# -*- coding: utf-8 -*-
"""Sustainable_Smart_City_Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iM226OFPXvYTolUbwqxaEn33TYnQkouR
"""

!pip install transformers accelerate sentencepiece

from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "ibm-granite/granite-3.3-2b-instruct"
hf_token = "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"

tokenizer = AutoTokenizer.from_pretrained(model_name, use_auth_token=hf_token)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    use_auth_token=hf_token,
    device_map="auto",
    torch_dtype="auto"
)

print("✅ Model loaded with Hugging Face token!")

input_text = "Suggest 3 sustainable habits for a working professional in a city."
inputs = tokenizer(input_text, return_tensors="pt").to("cuda")
outputs = model.generate(**inputs, max_new_tokens=500)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

!pip install streamlit pandas numpy plotly scikit-learn transformers torch PyMuPDF sentencepiece

!wget -q -O - ipv4.icanhazip.com

!streamlit run app.py & npx localtunnel --port 8501

